"""Settings loaded from .env; bootstraps autogenerated secrets on first run."""

import secrets
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict

ROOT = Path(__file__).resolve().parent.parent


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=ROOT / ".env", env_file_encoding="utf-8", extra="ignore")

    # required — key from ollama.com/settings/keys
    ollama_api_key: str = ""
    ollama_base_url: str = "https://ollama.com"

    # auth — autogenerated on first run when empty
    auth_password: str = ""
    secret_key: str = ""

    app_port: int = 8000
    cookie_secure: bool = False

    default_model: str = ""
    tool_max_iter: int = 8
    tool_result_max_chars: int = 20000
    history_max_messages: int = 40
    notes_snapshot_chars: int = 500

    pyexec_timeout: int = 8
    pyexec_network: bool = True


def _persist(key: str, value: str) -> None:
    """Append KEY=value to .env so the generated secret survives restarts."""
    env_path = ROOT / ".env"
    try:
        with open(env_path, "a", encoding="utf-8") as f:
            f.write(f"\n{key}={value}\n")
    except OSError:
        pass


def _bootstrap() -> Settings:
    s = Settings()
    generated: list[tuple[str, str]] = []
    if not s.secret_key:
        s.secret_key = secrets.token_urlsafe(32)
        generated.append(("SECRET_KEY", s.secret_key))
    if not s.auth_password:
        s.auth_password = secrets.token_urlsafe(12)
        generated.append(("AUTH_PASSWORD", s.auth_password))
    if generated:
        for key, value in generated:
            _persist(key, value)
        _print_banner(generated)
    return s


def _print_banner(generated: list[tuple[str, str]]) -> None:
    line = "=" * 62
    print("\n" + line)
    print("  FIRST RUN — autogenerated secrets written to .env")
    for key, value in generated:
        print(f"  {key} = {value}")
    print("  (password above is what you log in with)")
    print(line + "\n")


settings = _bootstrap()

if not settings.ollama_api_key:
    print(
        "\n[WARN] OLLAMA_API_KEY is empty — open "
        f"{(ROOT / '.env')} and fill the line OLLAMA_API_KEY=...\n"
        "(key from ollama.com/settings/keys; or run ./setkey.sh)\n"
    )